"""Mocked LLM response templates and scoping button definitions.

Product Intent:
    In production, these strings would be generated by an LLM.  Here they are
    pre-defined templates that ensure deterministic, reproducible demos.
    The ``com_style`` key on each template set lets the response node adapt
    tone without any external API call.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Scoping button definitions (NOT AI-generated — pre-designed per vertical)
# ---------------------------------------------------------------------------

SCOPING_BUTTONS: dict[str, list[str]] = {
    "digital": ["Look for a Brand", "Compare Models", "Find Max Cashback"],
    "travel": ["Family Trip", "Business Trip", "Leisure Trip"],
}

# Second-round scoping fields (travel only, after trip-type selection)
TRAVEL_FIELDS: list[dict[str, str]] = [
    {"label": "Travel group size", "field_type": "number"},
    {"label": "Starting date (YYYY-MM-DD)", "field_type": "date"},
    {"label": "End date (YYYY-MM-DD)", "field_type": "date"},
]

# ---------------------------------------------------------------------------
# Scoping prompt text (per intent, per round)
# ---------------------------------------------------------------------------

SCOPING_PROMPTS: dict[str, list[str]] = {
    "digital": [
        "How would you like to refine your phone search? Please select your preferred approach below.",
    ],
    "travel": [
        "What type of trip are you planning? Please select one of the options below.",
        "Thank you. To proceed with your {travel_type} trip, please provide the following details:",
    ],
}

# ---------------------------------------------------------------------------
# Response templates (keyed by com_style, then intent)
# ---------------------------------------------------------------------------

RESPONSE_TEMPLATES: dict[str, dict[str, str]] = {
    "formal": {
        "digital": "Based on your requirements, I have selected the following options for your consideration:\n\n{products}",
        "travel": "Here are the curated travel packages that match your requirements:\n\n{products}",
        "com_style": "Understood. I will adjust my communication style accordingly.",
        "general": "Welcome. I can assist you with finding digital products such as phones and tablets, or planning travel packages with competitive cashback rates. How may I help you today?",
    },
    "casual": {
        "digital": "Hey! Check these out \u2014 pretty solid options:\n\n{products}",
        "travel": "Awesome, here are some sweet deals I found:\n\n{products}",
        "com_style": "Sure thing! I'll keep it chill from now on. \U0001f60e",
        "general": "Hey there! Looking for a phone, tablet, or maybe a trip? Let me know!",
    },
    "concise": {
        "digital": "Here are your top picks:\n\n{products}",
        "travel": "Best travel deals for you:\n\n{products}",
        "com_style": "Got it \u2014 I'll keep things concise from here on.",
        "general": "Hi! I can help you find phones, tablets, or plan a trip. What are you looking for?",
    },
    "detailed": {
        "digital": "I've carefully selected the following options based on your criteria. Each listing includes verified cashback rates and detailed specifications:\n\n{products}",
        "travel": "Here are curated travel packages matching your requirements. All cashback rates have been verified and hotels are suited to your trip type:\n\n{products}",
        "com_style": "Understood. I will adopt a more detailed communication style going forward, providing comprehensive information in my responses.",
        "general": "Hello! I'm your SB shopping assistant. I can help you explore digital products like phones and tablets, or plan travel packages with the best cashback rates. What would you like to explore today?",
    },
}

# ---------------------------------------------------------------------------
# Session summary templates (mocked auto-conclusion)
# ---------------------------------------------------------------------------

SUMMARY_RULES: list[tuple[str, str]] = [
    ("camera", "User prioritises camera quality when choosing phones."),
    ("cashback", "User is cashback-driven and looks for maximum savings."),
    ("brand", "User is brand-conscious when selecting products."),
    ("business", "User frequently travels for business."),
    ("family", "User plans family trips."),
    ("leisure", "User enjoys leisure travel."),
    ("tablet", "User is interested in tablets."),
    ("phone", "User is interested in smartphones."),
    ("casual", "User prefers a casual communication style."),
    ("detailed", "User prefers detailed, comprehensive responses."),
    ("concise", "User prefers concise communication."),
]

DEFAULT_SUMMARY = "User explored general product options."


def generate_summary(conversation_text: str) -> str:
    """Produce a mocked session summary from a conversation transcript.

    Product Intent:
        In production this would be an LLM call.  Here, deterministic keyword
        matching ensures the same conversation always yields the same summary.
    """
    text_lower = conversation_text.lower()
    for keyword, summary in SUMMARY_RULES:
        if keyword in text_lower:
            return summary
    return DEFAULT_SUMMARY
