"""Conversation history storage and session summary generation.

Product Intent:
    Supports the "harness engineering" approach by persisting the most recent
    three conversations per user and generating an auto-conclusion after each
    session.  Together with the user profile, this data forms the context
    window assembled by ``memory/context.py`` for every future interaction.

    In production, conversation transcripts would be stored in a database and
    summaries would be generated by an LLM.  In this prototype, storage is
    backed by an in-memory dict (optionally persisted to ``mocks/conversations.json``)
    and summaries are produced by deterministic keyword logic so demos remain
    fully reproducible.
"""

from __future__ import annotations

from typing import Any


def get_recent_conversations(user_id: str, limit: int = 3) -> list[dict[str, Any]]:
    """Return the most recent *limit* conversations for a user.

    Product Intent:
        Provides the "last 3 conversations" portion of the context window.
        These are full transcripts, kept short so the mocked LLM can reason
        over them without an external API call.

    Args:
        user_id: Unique identifier for the user.
        limit: Maximum number of conversations to return (default 3).

    Returns:
        A list of conversation dicts, newest first.
    """
    # TODO: implement in-memory or JSON-backed retrieval keyed by user_id.
    raise NotImplementedError


def save_conversation(user_id: str, conversation: dict[str, Any]) -> None:
    """Persist a completed conversation for a user.

    Product Intent:
        After a session ends, the full transcript is stored so that future
        interactions can include it in the context window.  Only the most
        recent three are retained; older conversations are evicted.
    """
    # TODO: implement storage with a max-3 retention policy.
    raise NotImplementedError


def get_session_summary(user_id: str) -> str | None:
    """Return the stored session summary (auto-conclusion) for a user.

    Product Intent:
        The summary is a short, auto-generated conclusion refined after each
        session.  It captures durable preferences (e.g., "user tends to
        compare camera specs before buying") and is included in every future
        context window alongside the profile.
    """
    # TODO: implement retrieval from the store.
    raise NotImplementedError


def generate_session_summary(conversation: dict[str, Any]) -> str:
    """Produce a mocked session conclusion from a completed conversation.

    Product Intent:
        In production this would be an LLM call that distils the conversation
        into a concise preference summary.  Here, deterministic keyword
        extraction is used so demos remain reproducible.
    """
    # TODO: implement keyword-based summary logic (mocked LLM).
    raise NotImplementedError
